name: Deploy Addressables to GitHub Pages

on:
  push:
    branches:
      - main   # Deploy when pushing to main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload Addressables to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ServerData/Android
          publish_branch: gh-pages
